### ISSUE TITLE
Team The Crux (04/28/2020)

### ISSUE THREAD

**Issue by MuriloRoque** [glowreeyah/Hotelmania#2]
Recommendations:
- Fix the logo image when the screen is smaller;
- Min-width on 380px for all pages;
- Change the search result images for object-fit cover;
- If you want a better effect when clicking the "How it works button", just add the CSS property "scroll-behavior: smooth;" in the HTML tag.

Pros:
- Very responsive design in general;
- Everything works as intended.

**Comment by glowreeyah** [comment]
Your reviews were very helpful. Issues have been fixed. Thank you
